version: '2'


services:
  loadbalancer:
      build:
        context: ./APP-LB-RoundRobin
        dockerfile: Dockerfile
      depends_on:
        - web
      container_name: loadbalancer
      ports:
        - "8080:6001"

  web:
      build:
        context: ./LogService
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - "8085-8088:6001"

  db:
      image: mongo:latest
      container_name: db
      environment:
        MONGO_INITDB_DATABASE: myFirstDatabase
        MONGO_INITDB_ROOT_USERNAME: crhystianmol
        MONGO_INITDB_ROOT_PASSWORD: 3124037984
      volumes:
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - mongodb:/data/db
        - mongodb_config:/data/configdb
      ports:
        - 27017:27017
      command: mongod

volumes:
  mongodb:
  mongodb_config: